/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import logicaNegocio.Taller;
import logicaNegocio.Vehiculo;

/**
 *
 * @author DAM2Alu10
 */
public class JDialogFORMvehiculo extends javax.swing.JDialog {
    Taller taller;
    Vehiculo vehiculo;
    JDialogVehiculos jd;
    Boolean dia;
    ArrayList<JLabel> lista;
    DefaultComboBoxModel dom1, dom2,dom3;

    /**
     * Creates new form JDialogFORMvehiculo
     */
    public JDialogFORMvehiculo(java.awt.Dialog parent, boolean modal) {
        super(parent, "VEHICULO NUEVO", false);
        jd = (JDialogVehiculos) parent;
        initComponents();
        taller=jd.taller;
        dia = jd.dia;
        jLabelIcono.setIcon(new ImageIcon("img/añadir.png"));
        jLabelBotonCancelar.setIcon(new ImageIcon("img/cancelar.png"));
        jLabelBotonGuardar.setIcon(new ImageIcon("img/guardar.png"));

        lista = new ArrayList<>();
        lista.add(jLabelTitulo1);
        lista.add(jLabelTitulo2);
        lista.add(jLabelMatricula);
        lista.add(jLabelRepa);
        lista.add(jLabelTipo);
        lista.add(jLabelModelo);
        lista.add(jLabelMarca);
        lista.add(jLabelClienteDni);

        //Creamos elos combobox
        dom1 = new DefaultComboBoxModel();
        String labels1[] = {Vehiculo.TIPO_TURISMO, Vehiculo.TIPO_FURGONETA, Vehiculo.TIPO_MOTOCICLETA};
        dom1.removeAllElements();
        for (String s : labels1) {
            dom1.addElement(s);
        }
        jComboBoxTipo.setModel(dom1);

        dom2 = new DefaultComboBoxModel();
        String labels2[] = {"SI", "NO"};
        dom2.removeAllElements();
        for (String s : labels2) {
            dom2.addElement(s);
        }
        jComboBoxRepara.setModel(dom2);
        
         dom3 = new DefaultComboBoxModel();
        String labels3[] = new String[taller.getListaCliente().size()];
        for (int i = 0; i < taller.getListaCliente().size(); i++) {
            labels3[i]=taller.getListaCliente().get(i).getDni();
        }
        dom3.removeAllElements();
        for (String s : labels3) {
            dom3.addElement(s);
        }
        jComboBoxDNI.setModel(dom3);


        if (dia) {
            jPanelFondo.setBackground(Color.lightGray);
            lista.forEach(x -> x.setForeground(Color.black));

        } else {
            jPanelFondo.setBackground(Color.darkGray);
            lista.forEach(x -> x.setForeground(Color.white));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        jLabelBotonGuardar = new javax.swing.JLabel();
        jLabelBotonCancelar = new javax.swing.JLabel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelIcono = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jPanelInsercion = new javax.swing.JPanel();
        jLabelMatricula = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelMarca = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jLabelRepa = new javax.swing.JLabel();
        jComboBoxRepara = new javax.swing.JComboBox<>();
        jLabelModelo = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jLabelClienteDni = new javax.swing.JLabel();
        jComboBoxDNI = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));
        setResizable(false);

        jPanelFondo.setPreferredSize(new java.awt.Dimension(500, 268));

        jPanelBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelBotones.setOpaque(false);
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 0));

        jLabelBotonGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonGuardarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jLabelBotonGuardar);

        jLabelBotonCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonCancelarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jLabelBotonCancelar);

        jPanelTitulo.setOpaque(false);
        jPanelTitulo.setLayout(new java.awt.GridLayout(1, 0));

        jLabelIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelTitulo.add(jLabelIcono);

        jLabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo1.setText("DATOS  DEL");
        jPanelTitulo.add(jLabelTitulo1);

        jLabelTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo2.setText("VEHICULO");
        jPanelTitulo.add(jLabelTitulo2);

        jPanelInsercion.setOpaque(false);
        jPanelInsercion.setLayout(new java.awt.GridLayout(3, 4));

        jLabelMatricula.setText("  MATRICULA:");
        jPanelInsercion.add(jLabelMatricula);
        jPanelInsercion.add(jTextFieldMatricula);

        jLabelTipo.setText("    TIPO:");
        jPanelInsercion.add(jLabelTipo);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInsercion.add(jComboBoxTipo);

        jLabelMarca.setText("  MARCA:");
        jPanelInsercion.add(jLabelMarca);
        jPanelInsercion.add(jTextFieldMarca);

        jLabelRepa.setText("    EN REPARACION:");
        jPanelInsercion.add(jLabelRepa);

        jComboBoxRepara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInsercion.add(jComboBoxRepara);

        jLabelModelo.setText("  MODELO:");
        jPanelInsercion.add(jLabelModelo);

        jTextFieldModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldModeloKeyPressed(evt);
            }
        });
        jPanelInsercion.add(jTextFieldModelo);

        jLabelClienteDni.setText("    CLIENTE:");
        jPanelInsercion.add(jLabelClienteDni);

        jComboBoxDNI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInsercion.add(jComboBoxDNI);

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                    .addContainerGap(133, Short.MAX_VALUE)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(130, 130, 130)))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jPanelInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                    .addContainerGap(227, Short.MAX_VALUE)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(202, Short.MAX_VALUE)))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(jPanelInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBotonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonGuardarMouseClicked
        guardar();
    }//GEN-LAST:event_jLabelBotonGuardarMouseClicked

    private void jLabelBotonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelBotonCancelarMouseClicked

    private void jTextFieldModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldModeloKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            guardar();
        }
    }//GEN-LAST:event_jTextFieldModeloKeyPressed
    
    private void guardar() {
        boolean b = true;
        try {
            if (!jTextFieldMatricula.getText().toUpperCase().matches("^[0-9]{1,4}(?!.*(LL|CH))[BCDFGHJKLMNPRSTVWXYZ]{3}")) {
                throw new NoSuchFieldException();
            }
            if (jTextFieldMatricula.getText().isEmpty() || jTextFieldMarca.getText().isEmpty() || jTextFieldModelo.getText().isEmpty()) {
                throw new IndexOutOfBoundsException();
            }
            if (dom2.getSelectedItem().toString().equals("NO")) {
                b = false;
            }
            jd.anadeVehiculo(new Vehiculo(jTextFieldMatricula.getText().toUpperCase(), jTextFieldMarca.getText().toUpperCase(),
                    jTextFieldModelo.getText().toUpperCase(), dom1.getSelectedItem().toString(), b,dom3.getSelectedItem().toString()));
            
                
            jTextFieldMarca.setText("");
            jTextFieldMatricula.setText("");
            jTextFieldModelo.setText("");
        } catch (NoSuchFieldException e) {
            //matricula no valida
            JOptionPane.showMessageDialog(jd, "Matricula no valida (0000XXX)", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (IndexOutOfBoundsException e) {
            //campos vacios
            JOptionPane.showMessageDialog(jd, "Debe de rellenar todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e) {
            //campos vacios
            JOptionPane.showMessageDialog(jd, "Ya existe un vehículo con esa matrícula", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxDNI;
    private javax.swing.JComboBox<String> jComboBoxRepara;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelBotonCancelar;
    private javax.swing.JLabel jLabelBotonGuardar;
    private javax.swing.JLabel jLabelClienteDni;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelRepa;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelInsercion;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables

}
