/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;

/**
 *
 * @author DAM2Alu10
 */
public class JFramePruebaPantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form JFramePruebaPantallaInicio
     */
    public JFramePruebaPantallaInicio() {
        initComponents();
       // this.setExtendedState(MAXIMIZED_BOTH);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelBotonesFondo = new javax.swing.JPanel();
        jPanelBotones1 = new javax.swing.JPanel();
        jLabelBotonClientes = new javax.swing.JLabel();
        jLabelBotonReparaciones = new javax.swing.JLabel();
        jLabelBotonVehiculos = new javax.swing.JLabel();
        jToggleButtonDiaNoche = new javax.swing.JToggleButton();
        jPanelTituloFondo = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelRueda1 = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelRueda2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setSize(new java.awt.Dimension(1280, 720));

        jPanelFondo.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanelFondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanelFondo.setLayout(new java.awt.BorderLayout());

        jPanelBotonesFondo.setBackground(new java.awt.Color(204, 204, 204));

        jPanelBotones1.setOpaque(false);
        jPanelBotones1.setLayout(new java.awt.GridLayout());

        jLabelBotonClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBotonClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonClientesMouseClicked(evt);
            }
        });
        jPanelBotones1.add(jLabelBotonClientes);

        jLabelBotonReparaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonReparaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonReparacionesMouseClicked(evt);
            }
        });
        jPanelBotones1.add(jLabelBotonReparaciones);

        jLabelBotonVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBotonVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonVehiculosMouseClicked(evt);
            }
        });
        jPanelBotones1.add(jLabelBotonVehiculos);

        jToggleButtonDiaNoche.setAlignmentY(0.0F);
        jToggleButtonDiaNoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDiaNocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesFondoLayout = new javax.swing.GroupLayout(jPanelBotonesFondo);
        jPanelBotonesFondo.setLayout(jPanelBotonesFondoLayout);
        jPanelBotonesFondoLayout.setHorizontalGroup(
            jPanelBotonesFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonDiaNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanelBotonesFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBotonesFondoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelBotonesFondoLayout.setVerticalGroup(
            jPanelBotonesFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonDiaNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanelBotonesFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBotonesFondoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelFondo.add(jPanelBotonesFondo, java.awt.BorderLayout.PAGE_END);

        jPanelTitulo.setOpaque(false);
        jPanelTitulo.setLayout(new java.awt.GridLayout());

        jLabelRueda1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelTitulo.add(jLabelRueda1);

        jLabelTitulo1.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("Talleres");
        jPanelTitulo.add(jLabelTitulo1);

        jLabelTitulo2.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("Fitipaldi");
        jPanelTitulo.add(jLabelTitulo2);

        jLabelRueda2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanelTitulo.add(jLabelRueda2);

        jPanelTituloFondo.add(jPanelTitulo);

        jPanelFondo.add(jPanelTituloFondo, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFondo.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBotonClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonClientesMouseClicked
       
    }//GEN-LAST:event_jLabelBotonClientesMouseClicked

    private void jLabelBotonReparacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonReparacionesMouseClicked
        
    }//GEN-LAST:event_jLabelBotonReparacionesMouseClicked

    private void jLabelBotonVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonVehiculosMouseClicked
        
    }//GEN-LAST:event_jLabelBotonVehiculosMouseClicked

    private void jToggleButtonDiaNocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDiaNocheActionPerformed
        //Modo noche
        if (jToggleButtonDiaNoche.isSelected()) {
          
            //Modo día
        } else {
           

        }
    }//GEN-LAST:event_jToggleButtonDiaNocheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePruebaPantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePruebaPantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePruebaPantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePruebaPantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePruebaPantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelBotonClientes;
    private javax.swing.JLabel jLabelBotonReparaciones;
    private javax.swing.JLabel jLabelBotonVehiculos;
    private javax.swing.JLabel jLabelRueda1;
    private javax.swing.JLabel jLabelRueda2;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanelBotones1;
    private javax.swing.JPanel jPanelBotonesFondo;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelTituloFondo;
    private javax.swing.JToggleButton jToggleButtonDiaNoche;
    // End of variables declaration//GEN-END:variables
}
