/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import jdk.tools.jlink.resources.jlink;
import logicaNegocio.Taller;
import logicaNegocio.Vehiculo;

/**
 *
 * @author DAM2Alu10
 */
public class JDialogFORMreparacionNuevo extends javax.swing.JDialog {
    Taller taller;
    Vehiculo vehiculo;
    JDialogReparaciones jd;
    JFrameTaller jf;
    Boolean dia;
    ArrayList<JLabel> lista;
    DefaultComboBoxModel dom1,dom2,dom3;
         double[]precio={700,850,100,500,1000,1500};
        String labels3[] = {"Junta de la trocola","Filtro antipartículas","Cambio ruedas","Cadena de distribucion","Turbo","Embrague"};

    /**
     * Creates new form JDialogFORMvehiculo
     */
    public JDialogFORMreparacionNuevo(java.awt.Dialog parent, boolean modal) {
        super(parent, "VEHICULO NUEVO", false);
        jd = (JDialogReparaciones) parent;
        initComponents();
        taller=jd.taller;
        dia = jd.dia;
        jLabelIcono.setIcon(new ImageIcon("img/añadir.png"));
        jLabelBotonCancelar.setIcon(new ImageIcon("img/cancelar.png"));
        jLabelBotonGuardar.setIcon(new ImageIcon("img/guardar.png"));
        

        lista = new ArrayList<>();
        lista.add(jLabelTitulo1);
        lista.add(jLabelTitulo2);
        lista.add(jLabelMatricula);
        lista.add(jLabelFecha);
        lista.add(jLabelDNI);
        lista.add(jLabelAveria);
        lista.add(jLabelhoras);

        //Creamos los combobox
        dom1 = new DefaultComboBoxModel();
        String labels[] = new String[taller.getListaCliente().size()];
        for (int i = 0; i < taller.getListaCliente().size(); i++) {
            labels[i]=taller.getListaCliente().get(i).getDni();
        }
        dom1.removeAllElements();
        for (String s : labels) {
            dom1.addElement(s);
        }
        jComboBoxDNI.setModel(dom1);

        dom2= new DefaultComboBoxModel();
        String[]labels2= new String[taller.getListaVehiculo().size()];
        for (int i = 0; i < taller.getListaVehiculo().size(); i++) {
            labels2[i]=(String)taller.getListaVehiculo().get(i).getMatricula();
            
        }
        dom2.removeAllElements();
        for(String s: labels2){
            dom2.addElement(s);
            System.out.println(s);
        }
        jComboBoxMatricula.setModel(dom2);
        
        
        dom3 = new DefaultComboBoxModel();
       
        dom3.removeAllElements();
        for (String s : labels3) {
            dom3.addElement(s);
        }
        jComboBoxAverias.setModel(dom3);
        
        if (dia) {
            jPanelFondo.setBackground(Color.lightGray);
            lista.forEach(x -> x.setForeground(Color.black));

        } else {
            jPanelFondo.setBackground(Color.darkGray);
            lista.forEach(x -> x.setForeground(Color.white));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        jLabelBotonGuardar = new javax.swing.JLabel();
        jLabelBotonCancelar = new javax.swing.JLabel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelIcono = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jPanelInsercion = new javax.swing.JPanel();
        jLabelMatricula = new javax.swing.JLabel();
        jComboBoxMatricula = new javax.swing.JComboBox<>();
        jLabelDNI = new javax.swing.JLabel();
        jComboBoxDNI = new javax.swing.JComboBox<>();
        jLabelAveria = new javax.swing.JLabel();
        jComboBoxAverias = new javax.swing.JComboBox<>();
        jLabelFecha = new javax.swing.JLabel();
        jSpinnerFecha = new javax.swing.JSpinner();
        jLabelhoras = new javax.swing.JLabel();
        jSpinnerHoras = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));
        setResizable(false);

        jPanelFondo.setPreferredSize(new java.awt.Dimension(500, 268));

        jPanelBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelBotones.setOpaque(false);
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 0));

        jLabelBotonGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonGuardarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jLabelBotonGuardar);

        jLabelBotonCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonCancelarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jLabelBotonCancelar);

        jPanelTitulo.setOpaque(false);
        jPanelTitulo.setLayout(new java.awt.GridLayout(1, 0));

        jLabelIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelTitulo.add(jLabelIcono);

        jLabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitulo1.setText("NUEVA");
        jPanelTitulo.add(jLabelTitulo1);

        jLabelTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo2.setText(" REPARACIÓN");
        jPanelTitulo.add(jLabelTitulo2);

        jPanelInsercion.setOpaque(false);
        jPanelInsercion.setLayout(new java.awt.GridLayout(3, 4));

        jLabelMatricula.setText("  MATRICULA:");
        jPanelInsercion.add(jLabelMatricula);

        jComboBoxMatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInsercion.add(jComboBoxMatricula);

        jLabelDNI.setText("    DNI:");
        jPanelInsercion.add(jLabelDNI);

        jComboBoxDNI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInsercion.add(jComboBoxDNI);

        jLabelAveria.setText("  AVERÍA:");
        jPanelInsercion.add(jLabelAveria);

        jComboBoxAverias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInsercion.add(jComboBoxAverias);

        jLabelFecha.setText("    FECHA:");
        jPanelInsercion.add(jLabelFecha);

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha, "dd/MM/yyyy"));
        jPanelInsercion.add(jSpinnerFecha);

        jLabelhoras.setText("  HORAS:");
        jPanelInsercion.add(jLabelhoras);

        jSpinnerHoras.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanelInsercion.add(jSpinnerHoras);

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                    .addContainerGap(133, Short.MAX_VALUE)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(130, 130, 130)))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jPanelInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                    .addContainerGap(227, Short.MAX_VALUE)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(202, Short.MAX_VALUE)))
            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFondoLayout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(jPanelInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBotonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonGuardarMouseClicked
        guardar();
    }//GEN-LAST:event_jLabelBotonGuardarMouseClicked

    private void jLabelBotonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelBotonCancelarMouseClicked
    
    private void guardar() {
        double pre=0;
        for (int i = 0; i < labels3.length; i++) {
            if(labels3[i].equals(dom3.getSelectedItem().toString()))
                pre=precio[i];
        }
       
      taller.addParte(taller.getTodosParte().size()+1, dom1.getSelectedItem().toString(), dom2.getSelectedItem().toString(),
              (Date)jSpinnerFecha.getValue(), false, (int)jSpinnerHoras.getValue(), 0, jf.getDateFormat("03/03/0003"),
              pre,dom3.getSelectedItem().toString(),1);
      jd.actualiza();
      this.dispose();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxAverias;
    private javax.swing.JComboBox<String> jComboBoxDNI;
    private javax.swing.JComboBox<String> jComboBoxMatricula;
    private javax.swing.JLabel jLabelAveria;
    private javax.swing.JLabel jLabelBotonCancelar;
    private javax.swing.JLabel jLabelBotonGuardar;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelhoras;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelInsercion;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JSpinner jSpinnerHoras;
    // End of variables declaration//GEN-END:variables

}
