package Vista;

import static java.awt.Color.black;
import static java.awt.Color.white;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author carlo
 */
public class JFrameTaller extends javax.swing.JFrame {

    ImageIcon imagen, imagen2,imagen3,imagen4;

    /**
     * Creates new form JFrameTaller
     */
    public JFrameTaller() {
        super("Talleres Fitipaldi");
        initComponents();
        //Cambiamos el icono de la ventana
        setIconImage(new ImageIcon("img/taller.png").getImage());
        //Añadimos una imagen al formulario
        imagen = new ImageIcon("img/corporativa.png");
        jLabelImagen.setIcon(imagen);
        jLabelImagen.setBounds(150, 150, imagen.getIconWidth(), imagen.getIconHeight());
        imagen2 = new ImageIcon("img/claro.jpg");
        jLabelFondo.setIcon(imagen2);
        jLabelFondo.setBounds(150, 150, imagen2.getIconWidth(), imagen2.getIconHeight());
        imagen3= new ImageIcon("img/oscuro.jpg");
        imagen4= new ImageIcon("img/rueda.png");
        jLabelRueda1.setIcon(imagen4);
        jLabelRueda1.setBounds(150, 150, imagen3.getIconWidth(), imagen3.getIconHeight());
        jLabelRueda2.setIcon(imagen4);
        jLabelRueda2.setBounds(150, 150, imagen3.getIconWidth(), imagen3.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelRueda1 = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelRueda2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jToggleButtonDiaNoche = new javax.swing.JToggleButton();
        jLabelImagen = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabelRueda1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabelRueda1);

        jLabelTitulo1.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("Talleres");
        jPanel2.add(jLabelTitulo1);

        jLabelTitulo2.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("Fitipaldi");
        jPanel2.add(jLabelTitulo2);

        jLabelRueda2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(jLabelRueda2);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 600, 60));

        jSeparator3.setBackground(new java.awt.Color(204, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator3.setOpaque(true);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, -1));

        jSeparator4.setBackground(new java.awt.Color(204, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator4.setOpaque(true);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 600, -1));

        jToggleButtonDiaNoche.setText("Modo nocturno");
        jToggleButtonDiaNoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDiaNocheActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButtonDiaNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));
        jPanel1.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 260, 200));

        jLabelFondo.setOpaque(true);
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonDiaNocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDiaNocheActionPerformed
        boolean pulsado = false;
        if (jToggleButtonDiaNoche.isSelected()) {
            jToggleButtonDiaNoche.setText("Modo diurno");
            jLabelFondo.setIcon(imagen3);
            jLabelFondo.setBounds(150, 150, imagen3.getIconWidth(), imagen3.getIconHeight());
            jLabelTitulo1.setForeground(white);
            jLabelTitulo2.setForeground(white);
            
        }else{
            jToggleButtonDiaNoche.setText("Modo nocturno");
            jLabelFondo.setIcon(imagen2);
            jLabelFondo.setBounds(150, 150, imagen3.getIconWidth(), imagen3.getIconHeight());
            jLabelTitulo1.setForeground(black);
            jLabelTitulo2.setForeground(black);
        }

    }//GEN-LAST:event_jToggleButtonDiaNocheActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelRueda1;
    private javax.swing.JLabel jLabelRueda2;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton jToggleButtonDiaNoche;
    // End of variables declaration//GEN-END:variables
}
